
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biometric-recognition
  labels:
    app: biometric-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biometric-recognition
  template:
    metadata:
      labels:
        app: biometric-recognition
    spec:
      containers:
        - name: biometric-recognition
          image: 746630811636.dkr.ecr.us-east-1.amazonaws.com/biometric-recognition:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "s3://biometric-recognition-artifacts/biometric_model/final_model_20260307_200122.pth"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
