
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biometric-recognition
  labels:
    app: biometric-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biometric-recognition
  template:
    metadata:
      labels:
        app: biometric-recognition
    spec:
      containers:
        - name: biometric-recognition
          image: biometric-recognition:test
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "s3://world-model-v1/biometric_model/final_model_20260307_200122.pth"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
